### ISSUE TITLE
Why not clone the whole strategy into storage to avoid contract calls?

### ISSUE THREAD

**Issue by 0xMotto** [Velocimeter/v3-contracts#5]
https://github.com/Velocimeter/v3-contracts/blob/7ac4caa8b208fbbdffdf5b20ad4c9c63b3e7302a/contracts/carbon/CarbonVaultTwoTokens.sol#L18

**Comment by dawiddrzala** [comment]
when the trades are executed the param in the strategy changed so we need to load it again to get the current liqudity
