### ISSUE TITLE
Need approval to burn voucher before deleting strategy

### ISSUE THREAD

**Issue by 0xMotto** [Velocimeter/v3-contracts#8]
https://github.com/Velocimeter/v3-contracts/blob/7ac4caa8b208fbbdffdf5b20ad4c9c63b3e7302a/contracts/carbon/CarbonVaultTwoTokens.sol#L74

**Comment by dawiddrzala** [comment]
it is not needed the only check in carbon is if you are owner of NFT if (msg.sender != _voucher.ownerOf(strategyId)) {
            revert AccessDenied();
        }
